Email-Calendar-OneNote-View-Upload/Net7.Mvc/Pages/Calendar.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DotNetCoreRazor_MSGraph.Graph;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.Graph;
using Microsoft.Identity.Web;

namespace DotNetCoreRazor_MSGraph.Pages
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    public class CalendarModel : PageModel
    {
        private readonly ILogger<CalendarModel> _logger;
        private readonly GraphCalendarClient _graphCalendarClient;
        private readonly GraphProfileClient _graphProfileClient;
        private MailboxSettings MailboxSettings { get; set; }

        public IEnumerable<Event> Events  { get; private set; }

        public CalendarModel(ILogger<CalendarModel> logger, GraphCalendarClient graphCalendarClient, GraphProfileClient graphProfileClient)
        {
            _logger = logger;
            _graphCalendarClient = graphCalendarClient;
            _graphProfileClient = graphProfileClient;
        }

        public async Task OnGetAsync()
        {
            MailboxSettings = await _graphCalendarClient.GetUserMailboxSettings();
            var userTimeZone = (String.IsNullOrEmpty(MailboxSettings.TimeZone)) 
                                ? "Pacific Standard Time" : MailboxSettings.TimeZone;
            Events = await _graphCalendarClient.GetEvents(userTimeZone);
        }

        public string FormatDateTimeTimeZone(DateTimeTimeZone value)
        {
            // Parse the date/time string from Graph into a DateTime
            var graphDatetime = value.DateTime;
            if (DateTime.TryParse(graphDatetime, out DateTime dateTime)) 
            {
                var dateTimeFormat = $"{MailboxSettings.DateFormat} {MailboxSettings.TimeFormat}".Trim();
                if (!String.IsNullOrEmpty(dateTimeFormat)) {
                    return dateTime.ToString(dateTimeFormat);
                }
                else 
                {
                    return $"{dateTime.ToShortDateString()} {dateTime.ToShortTimeString()}";
                }
            }
            else
            {
                return graphDatetime;
            }
        }
    }
}

Email-Calendar-OneNote-View-Upload/Net7.Mvc/Pages/Email.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DotNetCoreRazor_MSGraph.Graph;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.Graph;
using Microsoft.Identity.Web;

namespace DotNetCoreRazor_MSGraph.Pages
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    public class EmailModel : PageModel
    {
        private readonly GraphEmailClient _graphEmailClient;
        
        [BindProperty(SupportsGet = true)]
        public string NextLink { get; set; }
        public IEnumerable<Message> Messages  { get; private set; }

        public EmailModel(GraphEmailClient graphEmailClient)
        {
            _graphEmailClient = graphEmailClient;
        }

        public async Task OnGetAsync()
        {
            var messagesPagingData = await _graphEmailClient.GetUserMessagesPage(NextLink); 
            Messages = messagesPagingData.Messages;
            NextLink = messagesPagingData.NextLink;
        }
    }
}

Email-Calendar-OneNote-View-Upload/Net7.Mvc/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace DotNetCoreRazor_MSGraph.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Email-Calendar-OneNote-View-Upload/Net7.Mvc/Pages/Files.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Text;
using System.Threading.Tasks;
using DotNetCoreRazor_MSGraph.Graph;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Graph;
using Microsoft.Identity.Web;

namespace DotNetCoreRazor_MSGraph.Pages
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    // Max supported upload size is 100MB
    [RequestFormLimits(MultipartBodyLengthLimit = 100000000)]
    [RequestSizeLimit(100000000)]
    public class FilesModel : PageModel
    {
        private readonly ILogger<FilesModel> _logger;
        private readonly GraphFilesClient _graphFilesClient;

        [BindProperty]
        public IFormFile UploadedFile { get; set; }
        public IDriveItemChildrenCollectionPage Files { get; private set; }

        public FilesModel(ILogger<FilesModel> logger, GraphFilesClient graphFilesClient)
        {
            _graphFilesClient = graphFilesClient;
            _logger = logger;
        }

        public async Task OnGetAsync()
        {
            Files = await _graphFilesClient.GetFiles(); 
        }

        public async Task OnPostAsync()
        {
            if (UploadedFile == null || UploadedFile.Length == 0)
            {
                return;
            }
 
            _logger.LogInformation($"Uploading {UploadedFile.FileName}.");

            using (var stream = new MemoryStream()) {
                await UploadedFile.CopyToAsync(stream);
                await _graphFilesClient.UploadFile(UploadedFile.FileName, stream);
            }
            await OnGetAsync();
        }

        public async Task<FileStreamResult> OnGetDownloadFile(string id, string name) {
            var stream = await _graphFilesClient.DownloadFile(id);
            return File(stream, MediaTypeNames.Application.Octet, name);
        }
    }
}

Email-Calendar-OneNote-View-Upload/Net7.Mvc/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using DotNetCoreRazor_MSGraph.Graph;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.Graph;
using Microsoft.Identity.Web;

namespace DotNetCoreRazor_MSGraph.Pages
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    public class IndexModel : PageModel
    {
        private readonly GraphProfileClient _graphProfileClient;
        public string UserDisplayName { get; private set; } = "";
        public string UserPhoto { get; private set; }
        readonly ITokenAcquisition _tokenAcquisition;
        readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, GraphProfileClient graphProfileClient, ITokenAcquisition tokenAcquisition)
        {
            _logger = logger;
            _graphProfileClient = graphProfileClient;
            _tokenAcquisition = tokenAcquisition;
        }

        public async Task OnGetAsync()
        {
            var user = await _graphProfileClient.GetUserProfile(); 
            UserDisplayName = user.DisplayName.Split(' ')[0];
            UserPhoto = await _graphProfileClient.GetUserProfileImage();
        }

        public async Task OnGetAccessTokenAsync() {
            // A simple example of getting an access token and making a call to Graph to retrieve the 
            // user's display name. You can view the token in the console (after running dotnet run).
            // Visit https://jwt.ms, copy the token into the textbox, and you can see the scopes available to the 
            // token in addition to other information.
            // https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-acquire-token?tabs=aspnetcore

            // Acquire the access token.
            string[] scopes = new string[]{"user.read"};
            string accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(scopes);
            _logger.LogInformation($"Token: {accessToken}");

            // Use the access token to call a protected web API.
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            string json = await client.GetStringAsync("https://graph.microsoft.com/v1.0/me?$select=displayName");
            _logger.LogInformation(json);
        }
    }
}

Email-Calendar-OneNote-View-Upload/Net7.Mvc/Pages/Calendar.cshtml
@page
@model CalendarModel
@{
    ViewData["Title"] = "ASP.NET Core and Microsoft Graph";
}

<div>
    <h1>Calendar Events</h1>
    @if (User.Identity.IsAuthenticated)
    {
        if (Model.Events != null && Model.Events.Any()) {
            @foreach(var evt in Model.Events) 
            {
                 <div class="card" style="width: 50rem;">
                    <div class="card-body">
                        <h5 class="card-title">
                            @evt.Subject 
                        </h5>
                        <p class="card-text">
                            <div class="container">
                                <div class="row">
                                    <div class="col-2">
                                        <strong>Start:</strong>
                                    </div>
                                    <div class="col">
                                        @Model.FormatDateTimeTimeZone(evt.Start)
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-2">
                                         <strong>End:</strong>
                                    </div>
                                    <div class="col">
                                        @Model.FormatDateTimeTimeZone(evt.End)
                                    </div>
                                </div>
                            </div>
                        </p>
                    </div>
                </div>
                <br />
            }
        }
        else {
            <div>No calendar events found</div>
        }
    }
    else
    {
        <a class="btn btn-primary btn-large" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Click here to sign in</a>
    }

    <br /><br />
    Learn how to build this page by going through the <strong><a href="https://docs.microsoft.com/learn/paths/m365-msgraph-dotnetcore-scenarios/?WT.mc_id=m365-30352-cxa" target="_blank">Explore Microsoft Graph scenarios for ASP.NET Core development</a></strong> learning path on Microsoft Learn.

</div>

Email-Calendar-OneNote-View-Upload/Net7.Mvc/Pages/Email.cshtml
@page
@model EmailModel
@{
    ViewData["Title"] = "ASP.NET Core and Microsoft Graph";
}

<div>
    <h1>Email</h1>
    @if (User.Identity.IsAuthenticated)
    {
        if (Model.Messages != null && Model.Messages.Any()) {
            @foreach(var message in Model.Messages) 
            {
                <div class="card" style="width: 50rem;">
                    <div class="card-body">
                        <h5 class="card-title">@message.Subject</h5>
                        <h6 class="card-subtitle mb-2 text-muted">@message.ReceivedDateTime.GetValueOrDefault().UtcDateTime</h6>
                        <p class="card-text">@message.BodyPreview</p>
                    </div>
                </div>
                <br />
            }
            @if (!String.IsNullOrEmpty(Model.NextLink)) {
                <a asp-page="/Email" asp-route-nextlink="@Model.NextLink" class="btn btn-primary">Next Page</a>
            }
        }
        else {
            <div>No Messages found</div>
        }
    }
    else
    {
        <a class="btn btn-primary btn-large" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Click here to sign in</a>
    }

    <br /><br />
    Learn how to build this page by going through the <strong><a href="https://docs.microsoft.com/learn/paths/m365-msgraph-dotnetcore-scenarios/?WT.mc_id=m365-30352-cxa" target="_blank">Explore Microsoft Graph scenarios for ASP.NET Core development</a></strong> learning path on Microsoft Learn.

</div>

Email-Calendar-OneNote-View-Upload/Net7.Mvc/Pages/Files.cshtml
@page
@model FilesModel
@{
    ViewData["Title"] = "Upload File";
}
 
<div>
    <h1>Files</h1>
    @if (User.Identity.IsAuthenticated) {

        <div>
            <!-- Add for file download -->
            @if (Model.Files != null && Model.Files.Count > 0) 
            {   
                <br />
                <label>Files in your OneDrive root folder:</label> @Model.Files.Count()
                <ul id="downloadLinks">
                    @foreach(var file in Model.Files) {
                        if (file.Folder == null && file.Package == null) {
                            <li>
                                <a asp-page-handler="DownloadFile" 
                                   asp-route-name="@file.Name"
                                   asp-route-id="@file.Id">@file.Name</a>
                            </li>
                        }
                    }
                </ul>
            }
            else 
            {
                <div>No files found</div>
            }
        </div>
    
        <br /><br />
        <h3>Upload File</h3>
        <hr />
        <form method="post" enctype="multipart/form-data">
            <input asp-for="UploadedFile" type="file">
            <input type="submit" value="Upload File">
        </form>

    }
    else
    {
        <a class="btn btn-primary btn-large" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Click here to sign in</a>
    }

    <br /><br />
    Learn how to build this page by going through the <strong><a href="https://docs.microsoft.com/learn/paths/m365-msgraph-dotnetcore-scenarios/?WT.mc_id=m365-30352-cxa" target="_blank">Explore Microsoft Graph scenarios for ASP.NET Core development</a></strong> learning path on Microsoft Learn.

</div>

Email-Calendar-OneNote-View-Upload/Net7.Mvc/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "ASP.NET Core and Microsoft Graph";
}

<div>
    <h1>ASP.NET Core and Microsoft Graph</h1>
    <br />
    @if (User.Identity.IsAuthenticated)
    {
        <h4>
            @if (Model.UserPhoto != null)
            {
                <img src="data:image/jpeg;base64, @Model.UserPhoto" class="user-photo nav-profile-photo rounded-circle align-self-center mr-2" />
            }
            Welcome @Model.UserDisplayName!</h4>
    }
    else
    {
        <a class="btn btn-primary btn-large" href="https://localhost:5001/signin-oidc">Click here to sign in</a>
    }
</div>